spring:
  profiles:
    active: local
  application:
    name: kafka
  kafka:
    bootstrap-servers: 0.0.0.0:9092
    properties:
      schema:
        registry:
          url: http://localhost:8081
  docker:
    compose:
      file:
        - ./docker/docker-compose.yaml
      readiness:
        wait: never
server:
  port: 8090

kafka:
  topics:
    topic-v1:
      name: com.bonespirito.stock.v1
      partitions: 3
      replicas: 1
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    topic-v2:
      name: com.bonespirito.stock.v2
      partitions: 3
      replicas: 1
      key-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
