spring:
  profiles:
    active: local
  application:
    name: kafka
  kafka:
    bootstrap-servers: 0.0.0.0:9092
    producer:
      key-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      group-id: my-group
    properties:
      schema:
        registry:
          url: http://localhost:8081
    bindings:
      stock-v1:
        producer:
          key-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      stock-v2:
        producer:
          key-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
  docker:
    compose:
      file:
        - ./docker/docker-compose.yaml
      readiness:
        wait: never
server:
  port: 8090
